name: "build"

on: [ "pull_request", "push" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2.3.4"
      - name: "Setup jdk 11"
        uses: "actions/setup-java@v1.4.3"
        with:
          java-version: "11"
      - name: "Assign permissions to gradlew"
        run: "chmod +x gradlew"
      - name: "Build"
        run: "./gradlew build"
