name: "build"

on: [ "pull_request", "push" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2.4.0"
      - name: "Setup jdk 11"
        uses: "actions/setup-java@v2"
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: "Assign permissions to gradlew"
        run: "chmod +x gradlew"
      - name: "Build"
        run: "./gradlew build"
